import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Navbar from '../components/Navbar'
// import Dummy from '../components/Dummy'


export default function Home() {
  console.log(styles);

  return (
    <div className={styles.container}>
      {/* <Dummy></Dummy> */}
    <style jsx>
    {`
      .mySpan{
        color:red
      }
      
    `}

    </style>
      <Head>
        <title>Shivam Coder Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="/sc.js"></script>
      </Head>
      {/* <Script src='/sc.js' strategy="lazyOnload">

      </Script> */}
      
      <main className={styles.main}>
        {blogs.map((blogItem)=>{
          <div className="blogItem">
          <h3>{blogItem.title}</h3>
          <p>Javascript is the language used to design logic for the web </p>
        </div>
        })}
        <h1 className={styles.title}>
          <span className="dummy"> Shivam Coder Blog</span>
       
        </h1>
        <Image src="/homeimg.jpg" width={237} height={158} className='myImg'  />
        <p className={styles.description}>
          A blog for coders by a coder 
        </p>
        <div className="blogs">
          <h2>Popular Blogs </h2>
            
            <div className="blogItem">
              <h3>How to learn flask</h3>
              <p>Javascript is the language used to design logic for the web </p>
            </div>
            <div className="blogItem">
              <h3>How to learn nextjs</h3>
              <p>Javascript is the language used to design logic for the web </p>
            </div>
        </div>
        
      </main>

      
    </div>
  )
}
